version: "3.8"

services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "11111:8080"
    command: --configfile /imposters/bank_simulator.ejs
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
  payment_gateway:
    container_name: payment_gateway
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_HTTPS_PORT=8080
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "80:80"
      - "8080:8080"
  mongoDB:
    container_name: mongoDB
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db_data/:/data/db